//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslateSeqApp.TranslateServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TranslateServer.ITranslateSeq")]
    public interface ITranslateSeq {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslateSeq/Translate", ReplyAction="http://tempuri.org/ITranslateSeq/TranslateResponse")]
        string Translate(string sequence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslateSeq/Translate", ReplyAction="http://tempuri.org/ITranslateSeq/TranslateResponse")]
        System.Threading.Tasks.Task<string> TranslateAsync(string sequence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslateSeq/TestFunc", ReplyAction="http://tempuri.org/ITranslateSeq/TestFuncResponse")]
        string TestFunc(string sequence);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslateSeq/TestFunc", ReplyAction="http://tempuri.org/ITranslateSeq/TestFuncResponse")]
        System.Threading.Tasks.Task<string> TestFuncAsync(string sequence);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITranslateSeqChannel : TranslateSeqApp.TranslateServer.ITranslateSeq, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TranslateSeqClient : System.ServiceModel.ClientBase<TranslateSeqApp.TranslateServer.ITranslateSeq>, TranslateSeqApp.TranslateServer.ITranslateSeq {
        
        public TranslateSeqClient() {
        }
        
        public TranslateSeqClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TranslateSeqClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslateSeqClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranslateSeqClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Translate(string sequence) {
            return base.Channel.Translate(sequence);
        }
        
        public System.Threading.Tasks.Task<string> TranslateAsync(string sequence) {
            return base.Channel.TranslateAsync(sequence);
        }
        
        public string TestFunc(string sequence) {
            return base.Channel.TestFunc(sequence);
        }
        
        public System.Threading.Tasks.Task<string> TestFuncAsync(string sequence) {
            return base.Channel.TestFuncAsync(sequence);
        }
    }
}
